### ISSUE TITLE
Use naming scheme for hazard map

### ISSUE THREAD

**Issue by kellpossible** [kellpossible/avalanche-report#19]
Currently hazard map has a fixed name, so it can fall out of sync with the current forecast.
I propose we use a naming scheme like:
`https://psavalancheconsulting.github.io/hazard-map/Gudauri_2023-02-12T20:00_LS.html`. We may need to use [url encoding](https://www.w3schools.com/tags/ref_urlencode.ASP) for the `:`, so it would look like `Gudauri_2023-02-12T20%3A00_LS.html`

Using this scheme will allow us to quickly/easily hook into the existing scheme for representing forecast files.

**Comment by kellpossible** [comment]
We're planning to move to using our own hazard map #39, and in the interim the manually generated hazard map is not being used, so this change is no longer required.

**Comment by PSAvalancheConsulting** [comment]
I was actually wondering the other day if we should bring back the 
interim map I had?

On 2024-01-27 12:31, Luke Frisken wrote:

> We're planning to move to using our own hazard map #39 [1], and in the 
> interim the manually generated hazard map is not being used, so this 
> change is no longer required.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were assigned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/kellpossible/avalanche-report/issues/39
[2] 
https://github.com/kellpossible/avalanche-report/issues/19#issuecomment-1913142993
[3]

**Comment by kellpossible** [comment]
@PSAvalancheConsulting  if you'd like to continue doing so, let me know. I think a simpler solution than this could be to only display the hazard map for the current forecast so we could continue doing it how we were before.

**Comment by kellpossible** [comment]
Although that may involve rendering multiple maps, which I'd like to avoid and just have them all combined in one interface with a layer selection dialog. Perhaps we could instead host the hazard layer separately and insert it into the current map, that may also not be too much work.

**Comment by PSAvalancheConsulting** [comment]
Would it not be possible to just insert a window that links to the 
website where the hazard map lives? That link is permanent.

On 2024-01-28 11:51, Luke Frisken wrote:

> Although that may involve rendering multiple maps, which I'd like to 
> avoid and just have them all combined in one interface with a layer 
> selection dialog. Perhaps we could instead host the hazard layer 
> separately and insert it into the current map, that may also not be too 
> much work.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/kellpossible/avalanche-report/issues/19#issuecomment-1913569786
[2]

**Comment by kellpossible** [comment]
@PSAvalancheConsulting we can do that on the home page I guess similar to what we did last season if you're happy to update it for every forecast, I can work on that tonight. Doing it on the forecast pages means that it won't remain in sync with the forecast on the page if someone goes back and looks in the archive.
